const assert=require('node:assert/strict'),fs=require('node:fs'),C=require('../assets/callpilot-demo-core.js');
const answers={issue:'Service request',type:'Homeowner',scope:'Leaking kitchen pipe',name:'Demo Customer',company:'Demo Construction',role:'Manager; contact Alex',city:'Montreal',address:'123 Demo Street',property:'Demo Apartments',unit:'4',safety:'No immediate danger',urgency:'Regular request',impact:'Office closed',access:'Call on arrival',authorization:'Yes, authorized',date:'October 15',time:'10 am',dispatch:'Today at 2 pm',phone:'514-555-0100',po:'None',original:'October 10 at 9 am',reason:'Please call me'};
function run(overrides={},settings={}){const call=C.newCall(settings),visited=[];for(let n=0;n<30;n++){const field=C.next(call);if(!field)return {call,visited};visited.push(field);assert.equal(C.answer(call,field,overrides[field]??answers[field]),null,field);}throw Error('Flow did not finish');}
for(const type of ['Homeowner','Contractor','Property manager','Business','Résidence','Entrepreneur','Gestionnaire immobilier','Entreprise']){const {call,visited}=run({type});assert.equal(call.values.scope,answers.scope);assert.equal(call.values.phone,'5145550100');assert(visited.includes('date'));assert(visited.includes('time'));if(call.type==='contractor')assert(visited.includes('po'));if(call.type==='property')assert(visited.includes('unit'));}
for(const issue of ['Cancel an appointment','Annuler un rendez-vous','Reschedule an appointment','Reporter un rendez-vous','Speak to the owner','Parler au propriétaire','Sales call','Sollicitation commerciale']){const {call}=run({issue});assert.notEqual(call.action,'service');assert(call.values.phone);assert(call.values.reason);if(call.action==='reschedule')assert(call.values.date&&call.values.time);}
const danger=run({safety:'Yes, immediate danger'});assert(danger.call.flags.includes('danger'));assert.equal(danger.call.action,'callback');assert(!danger.visited.includes('date'));
const urgent=run({urgency:'Emergency today'});assert(urgent.visited.includes('dispatch'));assert(!urgent.visited.includes('date'));
assert(run({city:'Toronto'},{areas:['Montréal']}).call.flags.includes('outside-area'));assert(!run({city:'Montreal'},{areas:['Montréal']}).call.flags.includes('outside-area'));
assert.equal(C.classify('I own a home and need a plumber'),'service');assert.equal(C.answer(C.newCall(),'phone','123'),'invalidPhone');assert.equal(C.answer(C.newCall(),'address','123'),'invalidAddress');assert.equal(C.answer(C.newCall(),'type','banana'),'unknownType');
const manifest=JSON.parse(fs.readFileSync('assets/ava-approved-questions.json'));for(const pair of Object.values({...C.fields,...C.messages}))pair.forEach((text,i)=>assert(manifest.some(c=>c.text===text&&c.lang===(i?'fr':'en')),text));
console.log('PASS complete bilingual demo paths, safety routing, request validation, service areas and original-voice coverage');
